BOARD_SOURCEFILES += board-leds.c
BOARD_SOURCEFILES += board-buttons.c
BOARD_SOURCEFILES += board-sensors.c

CFLAGS += -DBOARD_CONF_PATH=\"nrf52832-dk-conf.h\"
CFLAGS += -DBOARD_DEF_PATH=\"nrf52832-dk-def.h\"

### Include the common nrf52832 makefile
include $(PLATFORM_ROOT_DIR)/nrf52832/Makefile.nrf52832

CONTIKI_TARGET_DIRS += nrf52832/dk
