CFLAGS += -DBUILD_WITH_DEPLOYMENT=1

#----------------------------------------------------------------------------#
# NULLTB
#----------------------------------------------------------------------------#
ifeq ($(DEPLOYMENT), nulltb)
	MODULES += os/services/deployment/nulltb
endif

#----------------------------------------------------------------------------#
# D-CUBE
#----------------------------------------------------------------------------#
ifeq ($(DEPLOYMENT), dcube)
	MODULES += os/services/deployment/dcube
endif
