# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    post_install:
      - wget -nv https://sourceforge.net/projects/doxygen/files/rel-1.9.4/doxygen-1.9.4.linux.bin.tar.gz/download -O doxygen-1.9.4.linux.bin.tar.gz
      - tar zxf doxygen-1.9.4.linux.bin.tar.gz doxygen-1.9.4/bin/doxygen --strip-components 2 --one-top-level=tools/doxygen
      - rm doxygen-1.9.4.linux.bin.tar.gz

python:
  install:
    - requirements: tools/readthedocs/requirements.txt

sphinx:
  configuration: tools/readthedocs/conf.py
