BOARD_SOURCEFILES += board-leds.c
BOARD_SOURCEFILES += board-buttons.c
BOARD_SOURCEFILES += board-sensors.c

CFLAGS += -DBOARD_CONF_PATH=\"nrf52833-dk-conf.h\"
CFLAGS += -DBOARD_DEF_PATH=\"nrf52833-dk-def.h\"

### Include the common nrf52833 makefile
include $(PLATFORM_ROOT_DIR)/nrf52833/Makefile.nrf52833

CONTIKI_TARGET_DIRS += nrf52833/dk
