include $(CONTIKI)/Makefile.identify-target

# Include BR variant depending on platform and also generic BR code for all
# embedded platforms
MODULES += os/services/osf-border-router/$(TARGET)

ifneq ($(TARGET),native)
	MODULES += os/services/osf-border-router/embedded
endif
