name: build
permissions: write-all

on:
  workflow_call:
    secrets:
      personal_access_token:
        required: true
  
jobs:
  build:
    strategy:
      matrix:
        board:
          [
            # dwm1001,
            # dwm3001cdk, 
            # bluebite,
            # uwpcie,
            dk,
            # dc10",
          ]
      fail-fast: false  # Ensures all matrix jobs run even if one fails
    runs-on: ubuntu-latest
    container: contiker/contiki-ng
    timeout-minutes: 20    

    steps:
    - name: Install additional packages
      run: |
        sudo apt update -y
        sudo apt install -y python3.10 python3.10-venv nodejs tree
        
    - uses: actions/checkout@v4
      with:
          # We need this for 'git describe' to work
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.personal_access_token }}

    - name: Configure Git
      run: git config --global --add safe.directory /__w/flock/flock

      # Prevent an issue with an error on the repository ownership
    - name: Fix repository ownership
      run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
    
      # Only clone submodules we need
    - name: Checkout submodules
      run: |
        git submodule update --init arch/cpu/arm/CMSIS
        git submodule update --init arch/cpu/nrf/lib/nrfx
        git submodule update --init arch/cpu/nrf52840/lib/nrf52-sdk
        git submodule update --init os/net/security/tinydtls
        
    - name: Install Python developer depedancies
      run: |
        python3.10 -m venv .venv
        . .venv/bin/activate
        pip install -r requirements-dev.txt
        inv --list
    
    - name: Create dummy deployment table
      run: |
        ls
        mkdir -p os/services/deployment/nulltb
        touch os/services/deployment/nulltb/deployment-map-nulltb.c
        cat <<EOF > os/services/deployment/nulltb/deployment-map-nulltb.c
        #include "services/deployment/deployment.h"

        #if CONTIKI_TARGET_NRF52840
        const struct id_mac deployment_nulltb[] = {
            {0, {{0}}}};
        #else
        #warning "WARN: Unknown DEPLOYMENT target"
        #endif
        EOF
        cat <<EOF > os/services/deployment/nulltb/deployment-map-nulltb.h
        #ifndef DEPLOYMENT_MAP_NULLTB_H_
        #define DEPLOYMENT_MAP_NULLTB_H_

        #define DEPLOYMENT_MAPPING_LEN 1

        #endif /* DEPLOYMENT_MAP_NULLTB_H_ */
        EOF

    - name: Build and package
      run: |
        . .venv/bin/activate
        inv package -b ${{ matrix.board }} --output=packages

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "${{ matrix.board }}-packages"
        path: packages/*
        retention-days: 30
