name: pipeline
permissions: write-all

on:
  push:
    tags: "v*.*.*"
    branches: '*'
    paths-ignore:
      - "doc/**"
      - "README.md"
      - "CHANGELOG.md"
  pull_request:
    branches: '*'
    paths-ignore:
      - "doc/**"
      - "README.md"
      - "CHANGELOG.md"
  schedule:
    # Nightly at 12am
    - cron: "0 0 * * *"
  
jobs:
  build:
    uses: ./.github/workflows/build_pipeline.yml
    secrets:
      personal_access_token: ${{ secrets.PAT }}

  # hil_tests:
  #   needs: [build]
  #   uses: ./.github/workflows/hil-tests.yml
  #   secrets:
  #     personal_access_token: ${{ secrets.PAT }}

  release:
    # needs: [hil_tests]
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release.yml
    secrets:
      personal_access_token: ${{ secrets.PAT }}
